### ISSUE TITLE
convert demographic questionaire code into jspsych module

### ISSUE THREAD

**Issue by chrisbrickhouse** [chrisbrickhouse/jsPsych#1]
- [ ] #2 `jspsych-html-form-checkboxes`
 - [ ] #3 `jspsych-html-form-radiobuttons` (see [`jspsych-survey-multi-choice`](https://www.jspsych.org/plugins/jspsych-survey-multi-choice/))
 - [ ] #4 `jspsych-html-form-textboxes` (see [`jspsych-survey-text`](https://www.jspsych.org/plugins/jspsych-survey-text/))
 - [ ] #5 `jspsych-html-form-dropdown` (see [`jspsych-survey-multi-select`](https://www.jspsych.org/plugins/jspsych-survey-multi-select/)

See jspsych/jsPsych#135 and jspsych/jsPsych#1047
